/**
 * Sync vault tips markdown into a TypeScript module for bundling.
 * Source of truth (local vault): ORGANISATION/CORVIDAE PLUGIN/CORVIDAE PLUGIN.md
 * In CI the source is absent — keep the committed tips-content.ts.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = dirname(fileURLToPath(import.meta.url));
const pluginRoot = resolve(rootDir, "..");
const sourceMd = resolve(pluginRoot, "../../CORVIDAE PLUGIN.md");
const outTs = resolve(pluginRoot, "src/settings/tips-content.ts");

const CROW_PATH =
	"M12 3c-1.2 1.8-1.6 3.4-1.5 5.1-.9-.4-1.7-.5-2.6-.3-1.4.3-2.5 1.3-3.1 2.6-.4.8-.5 1.7-.3 2.6.3 1.3 1.2 2.4 2.5 2.9-.7.9-1 2-1 3.2 0 .4.3.7.7.7h.1c.3 0 .6-.2.7-.5.3-1 .8-1.8 1.6-2.4.5 1.4 1.5 2.5 2.9 3.1.3.1.7 0 .8-.3.1-.3 0-.7-.3-.8-1.1-.5-1.9-1.4-2.2-2.6 1.1.2 2.2 0 3.1-.6.9-.6 1.5-1.5 1.7-2.6.6.5 1.4.8 2.2.8.4 0 .7-.3.7-.7 0-.9-.3-1.7-.8-2.4.9-.3 1.6-1 2-1.9.2-.4 0-.9-.4-1.1-.4-.2-.9 0-1.1.4-.3.6-.8 1.1-1.5 1.3-.1-1.2-.6-2.3-1.5-3.1C13.6 4.6 12.9 3.7 12 3z";

const CROW_SVG =
	'<svg class="corvidae-crow-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="1em" height="1em" aria-hidden="true" focusable="false"><path fill="currentColor" d="' +
	CROW_PATH +
	'"/></svg>';

/** ZWJ black bird only (🐦‍⬛). */
const CROW_EMOJI_RE = /\u{1F426}\u{200D}\u{2B1B}/gu;

function transformTipsMarkdown(raw, version) {
	let md = raw;
	md = md.replace(
		/<title>CORVIDAE — Obsidian Plugin v[\d.]+<\/title>/,
		`<title>CORVIDAE — Obsidian Plugin v${version}</title>`
	);
	md = md.replace(CROW_EMOJI_RE, CROW_SVG);
	return md;
}

function toTsModule(markdown) {
	const escaped = markdown
		.replace(/\\/g, "\\\\")
		.replace(/`/g, "\\`")
		.replace(/\$\{/g, "\\${");
	return [
		"/**",
		" * Generated by scripts/sync-tips.mjs — do not edit by hand.",
		" * Source: ORGANISATION/CORVIDAE PLUGIN/CORVIDAE PLUGIN.md",
		" */",
		"",
		"export const TIPS_VAULT_PATH = \"CORVIDAE.md\";",
		"",
		"export const TIPS_MARKDOWN = `" + escaped + "`;",
		"",
	].join("\n");
}

const version = JSON.parse(
	readFileSync(resolve(pluginRoot, "manifest.json"), "utf8")
).version;

if (!existsSync(sourceMd)) {
	if (!existsSync(outTs)) {
		console.error(
			"Missing tips source and src/settings/tips-content.ts — cannot build."
		);
		process.exit(1);
	}
	console.log(
		"Source CORVIDAE PLUGIN.md not found (CI) — keeping committed tips-content.ts"
	);
	process.exit(0);
}

let source = readFileSync(sourceMd, "utf8");
const updatedSource = transformTipsMarkdown(source, version);
if (updatedSource !== source) {
	writeFileSync(sourceMd, updatedSource, "utf8");
	source = updatedSource;
	console.log("Updated source CORVIDAE PLUGIN.md (title + crow SVG)");
}

writeFileSync(outTs, toTsModule(source), "utf8");
console.log(`Wrote ${outTs} (${source.length} chars, v${version})`);
